### ISSUE TITLE
`oci-env pulpcore-manager reset_db` fails with not enough permissions

### ISSUE THREAD

**Issue by dkliban** [pulp/oci_env#17]
```
[dkliban@localhost oci_env]$ oci-env pulpcore-manager reset_db

You have requested a database reset.
This will IRREVERSIBLY DESTROY
ALL data in the database "pulp".
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
pulp [None]: root:INFO: Executing... "DROP DATABASE "pulp";"
pulp [None]: root:ERROR: Error: must be owner of database pulp
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django_extensions/management/commands/reset_db.py", line 175, in handle
    cursor.execute(drop_query)
psycopg2.errors.InsufficientPrivilege: must be owner of database pulp

pulp [None]: root:INFO: Executing... "CREATE DATABASE "pulp" WITH OWNER = "pulp"  ENCODING = 'UTF8';"
Traceback (most recent call last):
  File "/usr/local/bin/pulpcore-manager", line 8, in <module>
    sys.exit(manage())
  File "/src/pulpcore/pulpcore/app/manage.py", line 11, in manage
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django_extensions/management/commands/reset_db.py", line 190, in handle
    cursor.execute(create_query)
psycopg2.errors.InsufficientPrivilege: permission denied to create database

```

Possible workaround is to run `oci-env shell` and run `pulpcore-manager reset_db` from there.

**Comment by dkliban** [comment]
The workaround is to run `oci-env shell` and then execute `pulpcore-manager reset_db` from there

**Comment by bmbouter** [comment]
I get the same error when I do that.

**Comment by newswangerd** [comment]
Closing this since we have the `oci-env db reset` command.
